export const COLORS = {
  background: "#0f1115",
  panel: "#151922",
  panelAlt: "#171b24",
  border: "#313745",
  borderSoft: "#222733",
  text: "#ffffff",
  subtle: "#9ca3b5",
  muted: "#6f737a",
  accent: "#8fb4ff",
  success: "#8ec9a8",
  warning: "#d7bb7d",
  notificationBackground: "#4a3b12",
  danger: "#d98c8c",
  thinking: "#8a8f98",
  tool: "#8ab4f8",
  toolBackground: "#1b2230",
  toolCompleteBackground: "#12321f",
  user: "#ededed",
  userBackground: "#2a2f3a"
} as const;

export const SPINNER_FRAMES = ["⠋", "⠙", "⠹", "⠸", "⠼", "⠴", "⠦", "⠧", "⠇", "⠏"];

export const SYNTAX_STYLES = {
  default: { fg: COLORS.text },
  comment: { fg: "#6f7787", italic: true },
  keyword: { fg: "#c792ea", bold: true },
  string: { fg: "#c3e88d" },
  number: { fg: "#f78c6c" },
  constant: { fg: "#ffcb6b" },
  type: { fg: "#82aaff" },
  function: { fg: "#82aaff" },
  method: { fg: "#82aaff" },
  variable: { fg: "#f07178" },
  parameter: { fg: "#ff5370" },
  property: { fg: "#f2f2f2" },
  operator: { fg: "#89ddff" },
  punctuation: { fg: "#89ddff" },
  delimiter: { fg: "#89ddff" },
  tag: { fg: "#f07178" },
  attribute: { fg: "#ffcb6b" },
  escape: { fg: "#f78c6c" },
  boolean: { fg: "#f78c6c", bold: true },
  "markup.heading": { fg: COLORS.accent, bold: true },
  "markup.heading.1": { fg: COLORS.accent, bold: true },
  "markup.heading.2": { fg: "#a8c7ff", bold: true },
  "markup.heading.3": { fg: "#b7d4ff", bold: true },
  "markup.list": { fg: COLORS.warning },
  "markup.raw": { fg: "#a5d6ff" },
  "markup.strong": { fg: COLORS.text, bold: true },
  "markup.italic": { fg: COLORS.text, italic: true },
  "markup.strikethrough": { fg: COLORS.subtle, dim: true },
  "markup.link": { fg: COLORS.accent, underline: true },
  "markup.link.label": { fg: COLORS.accent, underline: true },
  "markup.link.url": { fg: COLORS.subtle, underline: true },
  "markup.quote": { fg: COLORS.subtle, italic: true }
} as const;
